name: CI - Test Python Changes

on:
  push:
    branches:
      - main
      - 'release/*'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository with full history
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. Setup Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e '.[dev,test]'
          pip install diff-cover jq

      # 4. Run tests with coverage
      - name: Run tests with coverage
        run: |
          pytest --cov=modulargeofm --cov-report=xml --cov-report=term-missing

      # 5. Check diff coverage
      - name: Check diff coverage (only new/changed code)
        id: diffcheck
        continue-on-error: true
        run: |
          # Run diff-cover and save output
          diff-cover coverage.xml --compare-branch=origin/main \
            --format json:diff.json \
            --format html:diff-cover.html \
            --fail-under=85 > diff_output.txt || true
          
          # Display diff-cover output
          cat diff_output.txt

          # Extract coverage from JSON
          if [ -s diff.json ]; then
              DIFF_COVERAGE=$(jq -r '.diff_covered_percent // 100' diff.json)
          else
              # No Python changes → default to 100%
              DIFF_COVERAGE=100
          fi

          echo "Diff coverage: $DIFF_COVERAGE%"
          echo "coverage=$DIFF_COVERAGE" >> $GITHUB_OUTPUT

      # 6. Upload HTML artifact
      - name: Upload HTML diff coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: diff-coverage-report
          path: diff-cover.html

      # 7. Fail workflow if Python diff coverage < threshold
      - name: check coverage threshold
        run: |
          COVERAGE=${{ steps.diffcheck.outputs.coverage}}
          echo "Diff coverage: $COVERAGE%"
          # Numeric comparison
          if (( $(echo "$COVERAGE < 85" | bc -l) )); then
            echo "❌ Diff coverage is below threshold"
            exit 1
          else
            echo "✅ Diff coverage meets threshold"
          fi
