name: CI - Test changes

on:
  push:
    branches:
      - main
      - 'release/*'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e '.[dev, test]'
          pip install diff-cover

      - name: Run tests with coverage
        run: |
          pytest --cov=modulargeofm --cov-report=xml
      
      - name: Check diff coverage (only new/changed code)
        id: diffcheck
        continue-on-error: true
        run: |
          diff-cover coverage.xml --compare-branch=origin/main --fail-under=85 > diff_output.txt || echo "diff-cover failed" >> diff_output.txt
          cat diff_output.txt
          # save coverage percentage for logging
          DIFF_COVERAGE=$(diff-cover coverage.xml --compare-branch=origin/main --json-report diff.json | jq '.diff_covered_percent')
          echo "Diff coverage: $DIFF_COVERAGE%"
          echo "coverage=$DIFF_COVERAGE" >> $GITHUB_OUTPUT
      
      - name: Generate HTML diff coverage report
        if: always()
        run: |
          diff-cover coverage.xml --compare-branch=origin/main --html-report diff-cover.html

      - name: Upload HTML diff coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
         name: diff-coverage-report
         path: diff-cover.html

      - name: Fail if diff coverage below threshold
        if: steps.diffcheck.outcome != 'success'
        run: exit 1
